<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Title>Resultron</Title>
        <PackageId>Resultron</PackageId>


        <Description>A robust and flexible C# library for implementing the Result pattern in .NET. Supports generic/non-generic results, fluent API with Map &amp; Bind, async operations, error aggregation, paged results, and implicit conversions — making your code cleaner and exception-free. </Description>

        <Authors>ferdikurnazdm</Authors>
        <Company>ferdikurnazdm</Company>

        <PackageProjectUrl>https://ferdikurnazdm.github.io/Resultron/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/ferdikurnazdm/Resultron</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <PackageTags>result;result-pattern;functional;error-handling;dotnet;csharp</PackageTags>

        <PackageIcon>logo.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        
        <Copyright>Copyright © 2025 ferdikurnazdm</Copyright>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt" />
        <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
    </ItemGroup>


    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\logo.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
